### ISSUE TITLE
Bug on Windows 10 (build 1809)

### ISSUE THREAD

**Issue by LunatikDev** [ToschAutomatisering/PS-NCentral#1]
Windows 10 (build 1809) doesn't recognize tls12 or tls13 as specified in your module
`[String]$AllProtocols = 'tls12,tls13'	## Https encryption`
What worked for me is replacing this line with:
`[String]$AllProtocols = 'Tls12'	## Https encryption`

**Comment by Robby-Swartenbroekx** [comment]
If you change that given line 81 mentioned above to the one below, you have the best of both worlds, uses TLS 1.3 if possible, but uses TLS 1.2 if the client doesn't support anything newer:
`[String]$AllProtocols = if (([Net.SecurityProtocolType]).DeclaredMembers.Name -contains "Tls13") { 'tls12,tls13' } else { 'tls12' }	## Https encryption - minimum Tls 1.2 needed`

**Comment by Robby-Swartenbroekx** [comment]
and if I would test it before I post an answer, I would have spotted that it needed to be put inside an @( ) like this:
`[String]$AllProtocols = @(if (([Net.SecurityProtocolType]).DeclaredMembers.Name -contains "Tls13") { 'tls12,tls13' } else { 'tls12' })	## Https encryption - minimum Tls 1.2 needed`

**Comment by ToschAutomatisering** [comment]
Modified as suggested by Robby-Swartenbroekx in version 1.5.
