### ISSUE TITLE
AddUser Class Not Working

### ISSUE THREAD

**Issue by ghost** [ToschAutomatisering/PS-NCentral#14]
Currently on N-Central 2022.7.0.26 and am unable to create users via the method userAdd() with the module.

The Module doesn't appear to have a method
![Screenshot 2022-11-14 at 9 15 04 AM](https://user-images.githubusercontent.com/110833124/201682270-f1fa1948-ca9b-44f0-808f-3436308dab68.png)

I've re-read the Add New User section found here https://github.com/AngryProgrammerInside/NC-API-Documentation 
![Screenshot 2022-11-14 at 9 17 24 AM](https://user-images.githubusercontent.com/110833124/201682822-5bb0b2dc-3913-42ce-a6ae-a481805d0511.png)

![Screenshot 2022-11-14 at 9 17 36 AM](https://user-images.githubusercontent.com/110833124/201682864-236116cd-f7dc-48b5-bb1c-1b3c488fc933.png)

**Comment by ToschAutomatisering** [comment]
Make sure you use the latest version. Should be 1.6 or higher, only available on Github at this moment. Will release in PS-Gallery soon.

**Comment by theonlytruebigmac** [comment]
I feel stupid, i had both so i just removed the ps-gallery one and yup you were right. Thanks for the reply! PEBCAK
