### ISSUE TITLE
Cannot Modify Device Custom Properties

### ISSUE THREAD

**Issue by dsmith0693** [ToschAutomatisering/PS-NCentral#16]
Whenever I try to modify device custom properties (either via the cmdlet or using the explicit method), I keep getting the following error:

```
Error : The remote server returned an error: (500) Internal Server Error.
soap:ReceiverMarshalling Error: class com.nable.nobj.ui2.DMSAPIException nor any of its super class is known to this context.
```

I see mention of a version 1.6 of PS-NCentral, but not seeing it available anywhere. I was wondering if the newer version possibly resolves this issue. Has anyone else had this issue?

**Comment by KennisBorger** [comment]
The issue seems to be related to the privileges/settings of the N-Central account used for API.- I don't think PS-NCentral v1.6 will solve this.
Version 1.6 (Beta) is currently available on the projects-site (See link in PS-Gallery) only. Will release soon after some more Q&A.
