### ISSUE TITLE
Pulling Registration Tokens

### ISSUE THREAD

**Issue by dsmith0693** [ToschAutomatisering/PS-NCentral#17]
We used to be able to pull registration tokens via this Powershell module, however after an update to N-Central we were no longer able to. Are the agent registration tokens no longer available to pull this way on N-Central update 2022.7? I don't see "registrationtoken" in the list of properties when pulling information from the customer list (it used to be listed here on previous versions of N-Central).

Thank you in advance.

**Comment by KennisBorger** [comment]
This data must be missing in the API-response. PS-NCentral only enumerates the returned key/value pairs.
