### ISSUE TITLE
LastLoggedInUser

### ISSUE THREAD

**Issue by baitsops** [ToschAutomatisering/PS-NCentral#4]
I don't seem to be able to get the return described here: https://documentation.n-able.com/N-central/troubleshooting/Content/kb/How-to-get-Last-Logged-In-User-for-a-device-from-N-central-API-using-SOAP-calls.htm

Any ideas?

**Comment by ToschAutomatisering** [comment]
This information is retrieved by the command **Get-NCDeviceList <CustomerID>**, which uses the **DeviceList** API specified in your link.
