### ISSUE TITLE
javax.validation.ValidationException: Unable to validate UI session

### ISSUE THREAD

**Issue by dkattan** [ToschAutomatisering/PS-NCentral#5]
The javax.validation.ValidationException: Unable to validate UI session error can be resolved by setting the password on the user the JWT was created for.

Posting this here so we can potentially update the comment block on the module to include that information.

**Comment by ToschAutomatisering** [comment]
Thank you.
Yes, this error is due to an expired password. Happens every 90 days bij default :-(

**Comment by LeonarddeR** [comment]
Would it be possible to change the error to be a bit more clear about the underlying issue?

**Comment by JimmyLuv69** [comment]
just wanted to say thanks for this. my API user stopped working, even after fresh JWT. 

i saw this and realized it was just over 1 year that i have been using that API account. it only accesses via JWT, but the password can still expire.. i reset password on the API account and viola! my API exports are working again.

thank you.

**Comment by Sigabiel** [comment]
Is there a way to disable this feature, so the password stops expiring. I am also only using the account via JWT access and resetting the password every 90 days seems like labor that can easily be forgotten, and I can't afford my app breaking every 90 days.

Is there a way to reset the password automatically?
