### ISSUE TITLE
soap:Receiver2100 Empty or null user name

### ISSUE THREAD

**Issue by AaronICT** [ToschAutomatisering/PS-NCentral#6]
I'm getting the following error when I try to use any of the Get commands:
soap:Receiver2100 Empty or null user name

This is the code I'm running:

PS /Users/xxx> Import-Module PS-NCentral
PS /Users/xxx> $ServerFQDN = “ncod104.n-able.com”
PS /Users/xxx> $JWT = "JSON Web Token removed to protect the innocent”
PS /Users/xxx> $NCConnection = New-NCentralConnection -ServerFQDN $ServerFQDN -JWT $JWT
PS /Users/xxx> $CustomerList = Get-NCCustomerList
Error : Response status code does not indicate success: 500 (Internal Server Error).
soap:Receiver2100 Empty or null user name.

Everything runs fine if I connect with the user name and password for the same user.

**Comment by ToschAutomatisering** [comment]
Maybe the JWT was regenerated for this user, invalidating the one you are using.
I'll try to replicate with a test-user.

**Comment by AaronICT** [comment]
Awesome! thank you! let me know what you come up with. If there is anything I can do to help, let me know.

**Comment by AaronICT** [comment]
OK, I just tried it again and it seems to be working. I think I didn't have the "API-Only User" checked. I also reset the token.
Sorry for the false alarm!

**Comment by ToschAutomatisering** [comment]
No Problem. Good to hear it's working now.
