### ISSUE TITLE
No exported functions

### ISSUE THREAD

**Issue by DevJxyden** [ToschAutomatisering/PS-NCentral#7]
No functions are exported from the psd1 file in v1.4 so nothing is callable.

**Comment by DevJxyden** [comment]
Found a note reading that functions should be individually exported

**Comment by ToschAutomatisering** [comment]
v1.4.1 will be released to fix this issue.

**Comment by ToschAutomatisering** [comment]
V1.4 Is published now. (1.4.1 on PowerShell Gallery)
