### ISSUE TITLE
Get Users and Add Users

### ISSUE THREAD

**Issue by eagle00789** [ToschAutomatisering/PS-NCentral#9]
Comming with the transition from AD to AAD sso, we need to recreate all users in nCentral to not be linked with an AD domain.
To do this we would like to programmaticly get the users and all user properties, convert them for use with AAD (azure sso) and create the new users. next we delete the old users to cleanup when everything works.
Currently with this very nice powershell module, this isn't available.
Do you have any idea when we will be able to get a list of all users including properties?

**Comment by ToschAutomatisering** [comment]
Unfortunately there is no direct option to list all users with their options.  You can however list the **groups** and **roles** with all members (Get-NCAccessGroupList / Get-NCUserRoleList). You can convert this information to see these settings per user.
In version 1.6 you can add users more easily, but you can only specify groups/roles during addition. There is no option to modify this later.
